### ISSUE TITLE
Fails to find Chromecast Audio

### ISSUE THREAD

**Issue by parkerlreed** [miniME89/chromecast-dbus#1]
Arch x86_64
Avahi-daemon is enabled and started

````
[parker@satellite ~]$ chromecast-dbus 
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
2017-03-06T07:01:32.179Z - info: [Chromecast] find client
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo -3008
    at errnoException (/usr/lib/node_modules/chromecast-dbus/node_modules/mdns/lib/resolver_sequence_tasks.js:199:11)
    at getaddrinfo_complete (/usr/lib/node_modules/chromecast-dbus/node_modules/mdns/lib/resolver_sequence_tasks.js:112:10)
    at GetAddrInfoReqWrap.oncomplete (/usr/lib/node_modules/chromecast-dbus/node_modules/mdns/lib/resolver_sequence_tasks.js:120:9)
````

**Comment by parkerlreed** [comment]
Fixed by enabling .local name resolution https://wiki.archlinux.org/index.php/avahi#Hostname_resolution
